.PHONY: everything_and_the_kitchen_sink

everything_and_the_kitchen_sink:
	@echo "Did you compile the program into a binary called log? If not, you have a problem my friend !"
	@echo "Did you run the log program to generate data.txt from data/noms.txt, data/prenoms.txt, data/cours.txt and data/sites.txt?"
	@echo "OK, then, let's generate the html file using data.txt and here we go:"
	./bin/data2html.sh data.txt data/index_template.html index.html
	@echo "Oh yeah, don't forget to copy the generated index.html to a folder with a css subdirectory"
